channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - c-compiler
  - cxx-compiler
  - mpi4py
  - hdf5=*=mpi_mpich*
  - pyyaml
  - pip
  - tqdm
  - pytest
  - pytest-mpi
  - pip:
    - pyyaml-include
    - h5py --no-binary=h5py
